### ISSUE TITLE
[ENHANCEMENT] Change Background Image Height from 725px to 100vh

### ISSUE THREAD

**Issue by Zindiks** [WisePace/landing#1]
### Description:
Currently, the height of the background image is set to 725px. I propose changing this to 100vh to ensure that the background image fills the entire viewport height, providing a more immersive experience across various screen sizes.

### Current Behavior:
Background height is set to 725px.
```html
<div class="relative bg-cover bg-center flex items-center justify-center" style="background-image: url('/assets/img/hero.webp'); height: 725px;">
```
<img width="1512" alt="Screenshot 2024-11-02 at 02 30 02" src="https://github.com/user-attachments/assets/dff6036c-87dd-4d49-88fa-5b78e7ef9b85">

### Proposed Change:

Update the CSS to set the background height to 100vh instead of 725px.
```html
<div class="relative bg-cover bg-center flex items-center justify-center" style="background-image: url('/assets/img/hero.webp'); height: 100vh;">
```
<img width="1512" alt="Screenshot 2024-11-02 at 02 33 19" src="https://github.com/user-attachments/assets/bbdea6a9-bdce-4d01-85e0-f5fb1d76ff64">

**Comment by KostLinux** [comment]
Changes done with rebranding of the page @Zindiks 

Thank you @Zindiks for contribution!
